apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-a-deployment
  labels:
    app: external-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: external-api
  template:
    metadata:
      labels:
        app: external-api
    spec:
      containers:
      - name: external-api
        image: kobigdocker/black_coordinates_a:v1
        ports:
        - containerPort: 8000
        env:
        - name: INTERNAL_URL
          value: "http://service-b-service:8001/items"
          