apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-a-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-a-deployment
  template:
    metadata:
      labels:
        app: service-a-deployment
    spec:
      containers:
      - name: service-a-container
        image: kobigdocker/black_coordinates_a:v1
        ports:
        - containerPort: 80