apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-b-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-b-deployment
  template:
    metadata:
      labels:
        app: service-b-deployment
    spec:
      containers:
      - name: service-b-container
        image: kobigdocker/black_coordinates_b:v1
        ports:
        - containerPort: 80